version: "3.9"

services:
  server:
    build:
      context: ./server
    container_name: backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always

  client:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "8081:80"
    depends_on:
      - server
    restart: always
